#!/bin/bash
# Script pour obtenir le token Plex

echo "🔑 Obtenir votre token Plex"
echo ""
echo "Méthode 1: Via l'API Plex (nécessite username/password)"
echo "--------------------------------------------------------"
echo ""
echo "Commande à exécuter:"
echo ""
echo "curl -X POST 'https://plex.tv/users/sign_in.xml' \\"
echo "  -H 'X-Plex-Client-Identifier: music-server' \\"
echo "  -H 'X-Plex-Product: Music Server' \\"
echo "  -H 'X-Plex-Version: 1.0' \\"
echo "  --user 'VOTRE_USERNAME:VOTRE_PASSWORD'"
echo ""
echo "Le token sera dans la réponse XML dans l'attribut 'authenticationToken'"
echo ""
echo "Méthode 2: Via le navigateur (plus simple)"
echo "-------------------------------------------"
echo "1. Ouvrez votre navigateur et allez sur https://app.plex.tv"
echo "2. Connectez-vous à votre compte Plex"
echo "3. Ouvrez les outils de développement (F12)"
echo "4. Allez dans l'onglet 'Network' (Réseau)"
echo "5. Rechargez la page (F5)"
echo "6. Cherchez une requête vers 'plex.tv' ou votre serveur Plex"
echo "7. Dans les en-têtes de la requête, cherchez 'X-Plex-Token'"
echo ""
echo "Méthode 3: Via l'interface Plex"
echo "-------------------------------"
echo "1. Allez sur https://www.plex.tv/claim"
echo "2. Connectez-vous à votre compte"
echo "3. Vous obtiendrez un token temporaire (valide 4 minutes)"
echo ""
echo "Une fois que vous avez votre token, créez un fichier .env avec:"
echo "PLEX_TOKEN=votre_token_ici"
echo "PLEX_SERVER_URL=http://127.0.0.1:32400"
echo "PLEX_LIBRARY_SECTION_ID=1"
echo ""

